import { CompanyProfile, Department, FuelDelivery, FuelExit, StockConfig, Supplier, User, Vehicle, VehicleCategory } from './types';

export const initialCompanyProfile: CompanyProfile = {
  isConfigured: false, // Prompt on startup
  name: 'GASCONS ENERGIE & BTP',
  legalStatus: 'SARL / Société Anonyme',
  taxId: 'RC: 16/00-0987625B • NIF: 001616098762541',
  activity: 'Travaux Publics, Terrassement, Carrière & Transport',
  logoUrl: '',
  phone: '+213 550 12 34 56 / +33 1 45 88 90 00',
  email: 'direction@gascons-tp.com',
  address: 'Zone Industrielle Voie 04, Lot 18',
  city: 'Alger / Paris',
  country: 'Algérie / France',
  currency: 'DZD',
  headerTagline: 'Gestion & Contrôle des Consommations de Gasoil & Flotte',
};

export const initialStockConfig: StockConfig = {
  initialStock: 12500,
  initialStockDate: '2026-08-01',
  tankCapacity: 25000,
  alertThreshold: 4000,
  criticalThreshold: 2000,
  tankName: 'Cuve Principale Gasoil - Dépôt Central',
  location: 'Zone Industrielle / Parc Engins',
};

export const initialUsers: User[] = [
  {
    id: 'usr-1',
    name: 'Ahmed Benali',
    email: 'ahmed.admin@gascons.com',
    role: 'ADMIN',
    department: 'Direction Générale',
    active: true,
    avatar: 'AB',
    password: 'admin',
    createdAt: '2026-01-10',
  },
  {
    id: 'usr-2',
    name: 'Moussa Traoré',
    email: 'moussa.stock@gascons.com',
    role: 'GESTIONNAIRE',
    department: 'Logistique & Stock',
    active: true,
    avatar: 'MT',
    password: 'stock',
    createdAt: '2026-01-15',
  },
  {
    id: 'usr-3',
    name: 'Karim Ouarad',
    email: 'karim.pompiste@gascons.com',
    role: 'POMPISTE',
    department: 'Exploitation & Dépôt',
    active: true,
    avatar: 'KO',
    password: 'pompe',
    createdAt: '2026-01-20',
  },
  {
    id: 'usr-4',
    name: 'Jean-Paul Koffi',
    email: 'jeanpaul.superviseur@gascons.com',
    role: 'SUPERVISEUR',
    department: 'Chantier Nord - Terrassement',
    active: true,
    avatar: 'JK',
    password: 'super',
    createdAt: '2026-02-01',
  },
];

export const initialDepartments: Department[] = [
  { id: 'dept-1', name: 'Logistique & Transport', manager: 'Moussa Traoré', code: 'LOG' },
  { id: 'dept-2', name: 'Chantier Nord - Terrassement', manager: 'Jean-Paul Koffi', code: 'CH-NORD' },
  { id: 'dept-3', name: 'Chantier Sud - Voirie', manager: 'Marc Diallo', code: 'CH-SUD' },
  { id: 'dept-4', name: 'Exploitation & Carrière', manager: 'Hassan Belkacem', code: 'EXP-CAR' },
  { id: 'dept-5', name: 'Atelier & Maintenance', manager: 'Brahim Ndiaye', code: 'MAINT' },
  { id: 'dept-6', name: 'Direction & Administration', manager: 'Ahmed Benali', code: 'DIR' },
];

export const initialCategories: VehicleCategory[] = [
  {
    id: 'cat-1',
    name: 'Poids Lourds & Bennes',
    unitType: 'KM',
    defaultTargetRate: 35.0, // L/100km
    description: 'Camions bennes, semi-remorques, porte-engins',
    color: '#3B82F6', // Blue
  },
  {
    id: 'cat-2',
    name: 'Engins de Chantier',
    unitType: 'HEURES',
    defaultTargetRate: 18.5, // L/h
    description: 'Pelles mécaniques, bulldozers, chargeuses, niveleuses',
    color: '#F59E0B', // Amber
  },
  {
    id: 'cat-3',
    name: 'Véhicules Utilitaires',
    unitType: 'KM',
    defaultTargetRate: 10.5, // L/100km
    description: 'Fourgons d intervention, pickups, navettes',
    color: '#10B981', // Emerald
  },
  {
    id: 'cat-4',
    name: 'Véhicules Légers (Liaison)',
    unitType: 'KM',
    defaultTargetRate: 7.2, // L/100km
    description: 'Véhicules de direction, supervision de chantiers',
    color: '#8B5CF6', // Purple
  },
  {
    id: 'cat-5',
    name: 'Groupes Électrogènes & Pompes',
    unitType: 'HEURES',
    defaultTargetRate: 12.0, // L/h
    description: 'Générateurs fixes et mobiles, motopompes',
    color: '#EC4899', // Pink
  },
];

export const initialVehicles: Vehicle[] = [
  {
    id: 'veh-1',
    code: 'PL-01',
    plateNumber: '4821-AB-16',
    name: 'Mercedes-Benz Actros 3340 (Benne 8x4)',
    categoryId: 'cat-1',
    departmentId: 'dept-1',
    tankCapacity: 400,
    currentReading: 124850,
    unitType: 'KM',
    assignedDriver: 'Omar Selmi',
    status: 'ACTIF',
  },
  {
    id: 'veh-2',
    code: 'PL-02',
    plateNumber: '7892-CD-16',
    name: 'Renault Trucks K440 (Tracteur)',
    categoryId: 'cat-1',
    departmentId: 'dept-1',
    tankCapacity: 450,
    currentReading: 98320,
    unitType: 'KM',
    assignedDriver: 'Mamadou Ba',
    status: 'ACTIF',
  },
  {
    id: 'veh-3',
    code: 'ENG-01',
    plateNumber: 'ENG-CAT-336',
    name: 'Pelle Hydraulique CAT 336D',
    categoryId: 'cat-2',
    departmentId: 'dept-2',
    tankCapacity: 620,
    currentReading: 4820,
    unitType: 'HEURES',
    assignedDriver: 'Yassine Cherif',
    status: 'ACTIF',
  },
  {
    id: 'veh-4',
    code: 'ENG-02',
    plateNumber: 'ENG-KOM-WA470',
    name: 'Chargeuse Komatsu WA470',
    categoryId: 'cat-2',
    departmentId: 'dept-4',
    tankCapacity: 380,
    currentReading: 3640,
    unitType: 'HEURES',
    assignedDriver: 'Abdelkader Saidi',
    status: 'ACTIF',
  },
  {
    id: 'veh-5',
    code: 'ENG-03',
    plateNumber: 'ENG-CAT-D8R',
    name: 'Bulldozer Caterpillar D8R',
    categoryId: 'cat-2',
    departmentId: 'dept-2',
    tankCapacity: 500,
    currentReading: 5120,
    unitType: 'HEURES',
    assignedDriver: 'Salif Keita',
    status: 'ACTIF',
  },
  {
    id: 'veh-6',
    code: 'UT-01',
    plateNumber: '1145-EF-16',
    name: 'Toyota Hilux 4x4 Double Cabine',
    categoryId: 'cat-3',
    departmentId: 'dept-2',
    tankCapacity: 80,
    currentReading: 68400,
    unitType: 'KM',
    assignedDriver: 'Jean-Paul Koffi',
    status: 'ACTIF',
  },
  {
    id: 'veh-7',
    code: 'UT-02',
    plateNumber: '3320-GH-16',
    name: 'Ford Ranger 4x4 Atelier Mobile',
    categoryId: 'cat-3',
    departmentId: 'dept-5',
    tankCapacity: 80,
    currentReading: 52100,
    unitType: 'KM',
    assignedDriver: 'Brahim Ndiaye',
    status: 'ACTIF',
  },
  {
    id: 'veh-8',
    code: 'VL-01',
    plateNumber: '9012-IJ-16',
    name: 'Dacia Duster 1.5 dCi Liaison',
    categoryId: 'cat-4',
    departmentId: 'dept-6',
    tankCapacity: 50,
    currentReading: 43200,
    unitType: 'KM',
    assignedDriver: 'Ahmed Benali',
    status: 'ACTIF',
  },
  {
    id: 'veh-9',
    code: 'GE-01',
    plateNumber: 'GE-SDMO-250',
    name: 'Groupe Électrogène SDMO 250 kVA (Fixe)',
    categoryId: 'cat-5',
    departmentId: 'dept-4',
    tankCapacity: 350,
    currentReading: 2150,
    unitType: 'HEURES',
    assignedDriver: 'Equipe Nuit Carrière',
    status: 'ACTIF',
  },
  {
    id: 'veh-10',
    code: 'GE-02',
    plateNumber: 'GE-CUM-100',
    name: 'Groupe Mobile Cummins 100 kVA',
    categoryId: 'cat-5',
    departmentId: 'dept-3',
    tankCapacity: 200,
    currentReading: 1480,
    unitType: 'HEURES',
    assignedDriver: 'Equipe Voirie Sud',
    status: 'ACTIF',
  },
];

export const initialSuppliers: Supplier[] = [
  {
    id: 'sup-1',
    name: 'TotalEnergies Distribution',
    contactName: 'Laurent Morel',
    phone: '+33 1 40 50 60 70',
    email: 'commandes@totalenergies-pro.com',
    address: 'Dépôt Pétrolier Portuaire Nord',
    pricePerLiter: 1.45,
  },
  {
    id: 'sup-2',
    name: 'Ola Energy Logistics',
    contactName: 'Samir Bouzid',
    phone: '+33 1 42 88 99 00',
    email: 'pro@olaenergy.com',
    address: 'Avenue des Hydrocarbures',
    pricePerLiter: 1.42,
  },
  {
    id: 'sup-3',
    name: 'Puma Energy B2B',
    contactName: 'Nathalie Meyer',
    phone: '+33 1 45 67 89 10',
    email: 'contact@pumaenergy.com',
    address: 'Terminal Carburants Sud',
    pricePerLiter: 1.44,
  },
];

export const initialDeliveries: FuelDelivery[] = [
  {
    id: 'del-1',
    deliveryNumber: 'BL-2026-0810',
    date: '2026-08-05',
    time: '09:30',
    supplierId: 'sup-1',
    quantityLiters: 10000,
    unitPrice: 1.45,
    totalCost: 14500,
    tankName: 'Cuve Principale Gasoil - Dépôt Central',
    driverName: 'Marc Dubois',
    truckPlate: '984-BL-75',
    receiverName: 'Moussa Traoré',
    notes: 'Livraison complète, contrôle densité conforme',
    createdAt: '2026-08-05T09:45:00Z',
  },
  {
    id: 'del-2',
    deliveryNumber: 'BL-2026-0842',
    date: '2026-08-16',
    time: '14:15',
    supplierId: 'sup-2',
    quantityLiters: 8000,
    unitPrice: 1.42,
    totalCost: 11360,
    tankName: 'Cuve Principale Gasoil - Dépôt Central',
    driverName: 'Rachid Touati',
    truckPlate: '441-TR-92',
    receiverName: 'Karim Ouarad',
    notes: 'Livraison programmée bi-mensuelle',
    createdAt: '2026-08-16T14:30:00Z',
  },
];

export const initialFuelExits: FuelExit[] = [
  // Semaine 31 (27 Juil - 02 Août)
  {
    id: 'exit-w31-1',
    ticketNumber: 'BS-2026-0001',
    date: '2026-07-29',
    time: '08:10',
    vehicleId: 'veh-1',
    categoryId: 'cat-1',
    departmentId: 'dept-1',
    quantityLiters: 320,
    previousReading: 122400,
    currentReading: 123300,
    distanceOrHours: 900,
    calculatedConsumption: 35.55,
    requesterName: 'Omar Selmi',
    pumpOperatorName: 'Karim Ouarad',
    signatureDataUrl: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="120" height="40"><path d="M10,25 Q30,5 60,20 T110,15" fill="none" stroke="%231e3a8a" stroke-width="2.5"/></svg>',
    purpose: 'Approvisionnement matériaux carrière',
    notes: 'Plein hebdomadaire',
    createdAt: '2026-07-29T08:10:00Z',
  },
  {
    id: 'exit-w31-2',
    ticketNumber: 'BS-2026-0002',
    date: '2026-07-31',
    time: '14:20',
    vehicleId: 'veh-3',
    categoryId: 'cat-2',
    departmentId: 'dept-2',
    quantityLiters: 390,
    previousReading: 4760,
    currentReading: 4780,
    distanceOrHours: 20,
    calculatedConsumption: 19.5,
    requesterName: 'Yassine Cherif',
    pumpOperatorName: 'Karim Ouarad',
    signatureDataUrl: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="120" height="40"><path d="M12,20 Q40,10 70,25 T105,10" fill="none" stroke="%231e3a8a" stroke-width="2.5"/></svg>',
    purpose: 'Fouille plateforme Chantier Nord',
    notes: 'Ravitaillement sur site',
    createdAt: '2026-07-31T14:20:00Z',
  },
  // Semaine 32 (03 Août - 09 Août)
  {
    id: 'exit-w32-1',
    ticketNumber: 'BS-2026-0003',
    date: '2026-08-04',
    time: '07:30',
    vehicleId: 'veh-2',
    categoryId: 'cat-1',
    departmentId: 'dept-1',
    quantityLiters: 310,
    previousReading: 97350,
    currentReading: 98200,
    distanceOrHours: 850,
    calculatedConsumption: 36.47,
    requesterName: 'Tariq Mansouri',
    pumpOperatorName: 'Karim Ouarad',
    signatureDataUrl: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="120" height="40"><path d="M8,22 Q35,8 65,18 T115,20" fill="none" stroke="%231e3a8a" stroke-width="2.5"/></svg>',
    purpose: 'Transfert gravier Chantier Sud',
    notes: 'Plein complet',
    createdAt: '2026-08-04T07:30:00Z',
  },
  {
    id: 'exit-w32-2',
    ticketNumber: 'BS-2026-0004',
    date: '2026-08-06',
    time: '09:45',
    vehicleId: 'veh-5',
    categoryId: 'cat-2',
    departmentId: 'dept-2',
    quantityLiters: 450,
    previousReading: 5095,
    currentReading: 5120,
    distanceOrHours: 25,
    calculatedConsumption: 18.0,
    requesterName: 'Salif Keita',
    pumpOperatorName: 'Karim Ouarad',
    signatureDataUrl: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="120" height="40"><path d="M15,25 Q50,12 80,22 T110,18" fill="none" stroke="%231e3a8a" stroke-width="2.5"/></svg>',
    purpose: 'Nivellement talus autoroute',
    notes: 'Plein réservoir 500L',
    createdAt: '2026-08-06T09:45:00Z',
  },
  {
    id: 'exit-w32-3',
    ticketNumber: 'BS-2026-0005',
    date: '2026-08-08',
    time: '16:00',
    vehicleId: 'veh-7',
    categoryId: 'cat-3',
    departmentId: 'dept-5',
    quantityLiters: 70,
    previousReading: 51400,
    currentReading: 52100,
    distanceOrHours: 700,
    calculatedConsumption: 10.0,
    requesterName: 'Brahim Ndiaye',
    pumpOperatorName: 'Karim Ouarad',
    signatureDataUrl: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="120" height="40"><path d="M10,18 Q40,30 75,12 T115,25" fill="none" stroke="%231e3a8a" stroke-width="2.5"/></svg>',
    purpose: 'Dépannage d urgence sur site Carrière',
    notes: 'Véhicule atelier',
    createdAt: '2026-08-08T16:00:00Z',
  },
  // Semaine 33 (10 Août - 16 Août)
  {
    id: 'exit-w33-1',
    ticketNumber: 'BS-2026-0006',
    date: '2026-08-11',
    time: '08:15',
    vehicleId: 'veh-1',
    categoryId: 'cat-1',
    departmentId: 'dept-1',
    quantityLiters: 300,
    previousReading: 123300,
    currentReading: 124050,
    distanceOrHours: 750,
    calculatedConsumption: 40.0,
    requesterName: 'Omar Selmi',
    pumpOperatorName: 'Karim Ouarad',
    signatureDataUrl: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="120" height="40"><path d="M10,25 Q30,5 60,20 T110,15" fill="none" stroke="%231e3a8a" stroke-width="2.5"/></svg>',
    purpose: 'Transport blocs béton',
    notes: 'RAS',
    createdAt: '2026-08-11T08:15:00Z',
  },
  {
    id: 'exit-w33-2',
    ticketNumber: 'BS-2026-0007',
    date: '2026-08-13',
    time: '11:00',
    vehicleId: 'veh-4',
    categoryId: 'cat-2',
    departmentId: 'dept-4',
    quantityLiters: 310,
    previousReading: 3608,
    currentReading: 3625,
    distanceOrHours: 17,
    calculatedConsumption: 18.23,
    requesterName: 'Abdelkader Saidi',
    pumpOperatorName: 'Karim Ouarad',
    signatureDataUrl: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="120" height="40"><path d="M12,28 Q35,5 80,18 T110,25" fill="none" stroke="%231e3a8a" stroke-width="2.5"/></svg>',
    purpose: 'Alimentation chargeuse carrière',
    notes: 'RAS',
    createdAt: '2026-08-13T11:00:00Z',
  },
  {
    id: 'exit-w33-3',
    ticketNumber: 'BS-2026-0008',
    date: '2026-08-15',
    time: '15:30',
    vehicleId: 'veh-10',
    categoryId: 'cat-5',
    departmentId: 'dept-3',
    quantityLiters: 180,
    previousReading: 1465,
    currentReading: 1480,
    distanceOrHours: 15,
    calculatedConsumption: 12.0,
    requesterName: 'Equipe Voirie Sud',
    pumpOperatorName: 'Karim Ouarad',
    signatureDataUrl: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="120" height="40"><path d="M10,20 Q50,35 75,10 T115,28" fill="none" stroke="%231e3a8a" stroke-width="2.5"/></svg>',
    purpose: 'Alimentation groupe mobile Chantier Sud',
    notes: 'Groupe Cummins 100kVA',
    createdAt: '2026-08-15T15:30:00Z',
  },
  // Semaine 34 (17 Août - 23 Août)
  {
    id: 'exit-w34-1',
    ticketNumber: 'BS-2026-0009',
    date: '2026-08-18',
    time: '07:15',
    vehicleId: 'veh-1',
    categoryId: 'cat-1',
    departmentId: 'dept-1',
    quantityLiters: 280,
    previousReading: 124050,
    currentReading: 124850,
    distanceOrHours: 800,
    calculatedConsumption: 35.0,
    requesterName: 'Omar Selmi',
    pumpOperatorName: 'Karim Ouarad',
    signatureDataUrl: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="120" height="40"><path d="M10,25 Q30,5 60,20 T110,15" fill="none" stroke="%231e3a8a" stroke-width="2.5"/></svg>',
    purpose: 'Rotation transport granulats Chantier Nord',
    notes: 'Plein complet avant départ',
    createdAt: '2026-08-18T07:15:00Z',
  },
  {
    id: 'exit-w34-2',
    ticketNumber: 'BS-2026-0010',
    date: '2026-08-19',
    time: '08:00',
    vehicleId: 'veh-3',
    categoryId: 'cat-2',
    departmentId: 'dept-2',
    quantityLiters: 420,
    previousReading: 4798,
    currentReading: 4820,
    distanceOrHours: 22,
    calculatedConsumption: 19.09,
    requesterName: 'Yassine Cherif',
    pumpOperatorName: 'Karim Ouarad',
    signatureDataUrl: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="120" height="40"><path d="M15,30 Q40,10 70,25 T105,10" fill="none" stroke="%231e3a8a" stroke-width="2.5"/></svg>',
    purpose: 'Terrassement Plateforme B1',
    notes: 'Ravitaillement par camion citerne mobile',
    createdAt: '2026-08-19T08:00:00Z',
  },
  {
    id: 'exit-w34-3',
    ticketNumber: 'BS-2026-0011',
    date: '2026-08-20',
    time: '11:30',
    vehicleId: 'veh-6',
    categoryId: 'cat-3',
    departmentId: 'dept-2',
    quantityLiters: 65,
    previousReading: 67780,
    currentReading: 68400,
    distanceOrHours: 620,
    calculatedConsumption: 10.48,
    requesterName: 'Jean-Paul Koffi',
    pumpOperatorName: 'Karim Ouarad',
    signatureDataUrl: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="120" height="40"><path d="M10,20 Q50,35 75,10 T115,28" fill="none" stroke="%231e3a8a" stroke-width="2.5"/></svg>',
    purpose: 'Tournée inspection chantiers',
    notes: 'RAS',
    createdAt: '2026-08-20T11:30:00Z',
  },
  {
    id: 'exit-w34-4',
    ticketNumber: 'BS-2026-0012',
    date: '2026-08-21',
    time: '06:45',
    vehicleId: 'veh-4',
    categoryId: 'cat-2',
    departmentId: 'dept-4',
    quantityLiters: 290,
    previousReading: 3625,
    currentReading: 3640,
    distanceOrHours: 15,
    calculatedConsumption: 19.33,
    requesterName: 'Abdelkader Saidi',
    pumpOperatorName: 'Karim Ouarad',
    signatureDataUrl: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="120" height="40"><path d="M12,28 Q35,5 80,18 T110,25" fill="none" stroke="%231e3a8a" stroke-width="2.5"/></svg>',
    purpose: 'Chargement concasseur carrière',
    notes: 'Niveau d huile vérifié',
    createdAt: '2026-08-21T06:45:00Z',
  },
  {
    id: 'exit-w34-5',
    ticketNumber: 'BS-2026-0013',
    date: '2026-08-22',
    time: '16:20',
    vehicleId: 'veh-9',
    categoryId: 'cat-5',
    departmentId: 'dept-4',
    quantityLiters: 240,
    previousReading: 2130,
    currentReading: 2150,
    distanceOrHours: 20,
    calculatedConsumption: 12.0,
    requesterName: 'Equipe Nuit Carrière',
    pumpOperatorName: 'Karim Ouarad',
    signatureDataUrl: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="120" height="40"><path d="M8,18 Q45,2 70,30 T112,12" fill="none" stroke="%231e3a8a" stroke-width="2.5"/></svg>',
    purpose: 'Alimentation centrale à béton & éclairage de nuit',
    notes: 'Fonctionnement continu',
    createdAt: '2026-08-22T16:20:00Z',
  },
  {
    id: 'exit-w34-6',
    ticketNumber: 'BS-2026-0014',
    date: '2026-08-23',
    time: '10:10',
    vehicleId: 'veh-8',
    categoryId: 'cat-4',
    departmentId: 'dept-6',
    quantityLiters: 42,
    previousReading: 42600,
    currentReading: 43200,
    distanceOrHours: 600,
    calculatedConsumption: 7.0,
    requesterName: 'Ahmed Benali',
    pumpOperatorName: 'Karim Ouarad',
    signatureDataUrl: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="120" height="40"><path d="M15,15 Q50,30 85,12 T118,22" fill="none" stroke="%231e3a8a" stroke-width="2.5"/></svg>',
    purpose: 'Déplacement administratif & audit',
    notes: 'Véhicule de direction',
    createdAt: '2026-08-23T10:10:00Z',
  },
];
