import { createClient, SupabaseClient } from '@supabase/supabase-js';

const STORAGE_KEY_SUPABASE_URL = 'gascons_supabase_url';
const STORAGE_KEY_SUPABASE_KEY = 'gascons_supabase_anon_key';

// Retrieve configuration from env variables or localStorage
export function getStoredSupabaseConfig() {
  const envUrl = (import.meta as any).env?.VITE_SUPABASE_URL || '';
  const envKey = (import.meta as any).env?.VITE_SUPABASE_ANON_KEY || '';

  const storedUrl = typeof window !== 'undefined' ? localStorage.getItem(STORAGE_KEY_SUPABASE_URL) || '' : '';
  const storedKey = typeof window !== 'undefined' ? localStorage.getItem(STORAGE_KEY_SUPABASE_KEY) || '' : '';

  return {
    url: storedUrl || envUrl || '',
    anonKey: storedKey || envKey || '',
    isConfigured: !!((storedUrl || envUrl) && (storedKey || envKey)),
  };
}

export function saveSupabaseConfig(url: string, anonKey: string) {
  if (typeof window !== 'undefined') {
    if (url) {
      localStorage.setItem(STORAGE_KEY_SUPABASE_URL, url.trim());
    } else {
      localStorage.removeItem(STORAGE_KEY_SUPABASE_URL);
    }
    if (anonKey) {
      localStorage.setItem(STORAGE_KEY_SUPABASE_KEY, anonKey.trim());
    } else {
      localStorage.removeItem(STORAGE_KEY_SUPABASE_KEY);
    }
    // Re-initialize client
    supabaseInstance = null;
  }
}

let supabaseInstance: SupabaseClient | null = null;

export function getSupabaseClient(): SupabaseClient | null {
  if (supabaseInstance) {
    return supabaseInstance;
  }

  const { url, anonKey, isConfigured } = getStoredSupabaseConfig();
  if (!isConfigured || !url || !anonKey) {
    return null;
  }

  try {
    supabaseInstance = createClient(url, anonKey, {
      auth: {
        persistSession: true,
        autoRefreshToken: true,
      },
    });
    return supabaseInstance;
  } catch (error) {
    console.error('Erreur lors de l\'initialisation du client Supabase:', error);
    return null;
  }
}

export async function testSupabaseConnection(): Promise<{
  connected: boolean;
  message: string;
  tables?: string[];
}> {
  const client = getSupabaseClient();
  if (!client) {
    return {
      connected: false,
      message: 'Supabase n\'est pas encore configuré (URL ou clé Anon manquante).',
    };
  }

  try {
    // Try to query or check connection
    const { data, error } = await client.from('company_profiles').select('count', { count: 'exact', head: true });
    
    if (error) {
      // If table doesn't exist yet, it means connection works but tables need migration
      if (error.code === '42P01' || error.message?.includes('does not exist')) {
        return {
          connected: true,
          message: 'Connecté à Supabase avec succès ! Les tables doivent être créées via le script SQL fourni.',
        };
      }
      return {
        connected: false,
        message: `Erreur Supabase: ${error.message}`,
      };
    }

    return {
      connected: true,
      message: 'Connecté à Supabase & synchronisation opérationnelle !',
    };
  } catch (error: any) {
    return {
      connected: false,
      message: error?.message || 'Impossible de joindre le serveur Supabase.',
    };
  }
}

// SQL Schema for users to run in Supabase SQL Editor
export const SUPABASE_SQL_SCHEMA = `-- ==========================================================
-- GASCONS : Script d'initialisation complet pour SUPABASE
-- À coller et exécuter dans l'éditeur SQL de votre projet Supabase
-- ==========================================================

-- 1. Table Profil Entreprise
CREATE TABLE IF NOT EXISTS public.company_profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  is_configured BOOLEAN NOT NULL DEFAULT false,
  name TEXT NOT NULL DEFAULT '',
  legal_status TEXT,
  tax_id TEXT,
  activity TEXT,
  logo_url TEXT,
  phone TEXT,
  email TEXT,
  address TEXT,
  city TEXT,
  country TEXT,
  currency TEXT DEFAULT 'DZD',
  header_tagline TEXT,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Table Configuration du Stock de Gasoil
CREATE TABLE IF NOT EXISTS public.stock_configs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  initial_stock DOUBLE PRECISION NOT NULL DEFAULT 0,
  initial_stock_date TEXT NOT NULL DEFAULT '',
  tank_capacity DOUBLE PRECISION NOT NULL DEFAULT 20000,
  alert_threshold DOUBLE PRECISION NOT NULL DEFAULT 3000,
  critical_threshold DOUBLE PRECISION NOT NULL DEFAULT 1500,
  tank_name TEXT NOT NULL DEFAULT 'Cuve Principale',
  location TEXT NOT NULL DEFAULT 'Dépôt Central',
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Table Catégories de Véhicules / Engins
CREATE TABLE IF NOT EXISTS public.vehicle_categories (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  unit_type TEXT NOT NULL DEFAULT 'KM',
  default_target_rate DOUBLE PRECISION NOT NULL DEFAULT 30,
  description TEXT,
  color TEXT NOT NULL DEFAULT '#3b82f6',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Table Départements / Chantiers
CREATE TABLE IF NOT EXISTS public.departments (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  manager TEXT NOT NULL DEFAULT '',
  code TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Table Véhicules & Engins
CREATE TABLE IF NOT EXISTS public.vehicles (
  id TEXT PRIMARY KEY,
  code TEXT NOT NULL,
  plate_number TEXT NOT NULL,
  name TEXT NOT NULL,
  category_id TEXT REFERENCES public.vehicle_categories(id) ON DELETE SET NULL,
  department_id TEXT REFERENCES public.departments(id) ON DELETE SET NULL,
  tank_capacity DOUBLE PRECISION NOT NULL DEFAULT 200,
  current_reading DOUBLE PRECISION NOT NULL DEFAULT 0,
  unit_type TEXT NOT NULL DEFAULT 'KM',
  assigned_driver TEXT,
  status TEXT NOT NULL DEFAULT 'ACTIF',
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. Table Fournisseurs de Carburant
CREATE TABLE IF NOT EXISTS public.suppliers (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  contact_name TEXT NOT NULL DEFAULT '',
  phone TEXT NOT NULL DEFAULT '',
  email TEXT,
  address TEXT,
  price_per_liter DOUBLE PRECISION NOT NULL DEFAULT 30,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 7. Table Sorties de Gasoil (Distributions & Bons)
CREATE TABLE IF NOT EXISTS public.fuel_exits (
  id TEXT PRIMARY KEY,
  ticket_number TEXT UNIQUE NOT NULL,
  date TEXT NOT NULL,
  time TEXT NOT NULL DEFAULT '12:00',
  vehicle_id TEXT REFERENCES public.vehicles(id) ON DELETE SET NULL,
  category_id TEXT,
  department_id TEXT,
  quantity_liters DOUBLE PRECISION NOT NULL,
  previous_reading DOUBLE PRECISION NOT NULL DEFAULT 0,
  current_reading DOUBLE PRECISION NOT NULL DEFAULT 0,
  distance_or_hours DOUBLE PRECISION NOT NULL DEFAULT 0,
  calculated_consumption DOUBLE PRECISION NOT NULL DEFAULT 0,
  requester_name TEXT NOT NULL DEFAULT '',
  pump_operator_name TEXT NOT NULL DEFAULT '',
  signature_data_url TEXT,
  purpose TEXT,
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 8. Table Livraisons & Réceptions Cuve
CREATE TABLE IF NOT EXISTS public.fuel_deliveries (
  id TEXT PRIMARY KEY,
  delivery_number TEXT NOT NULL,
  date TEXT NOT NULL,
  time TEXT NOT NULL DEFAULT '12:00',
  supplier_id TEXT REFERENCES public.suppliers(id) ON DELETE SET NULL,
  quantity_liters DOUBLE PRECISION NOT NULL,
  unit_price DOUBLE PRECISION NOT NULL DEFAULT 0,
  total_cost DOUBLE PRECISION NOT NULL DEFAULT 0,
  tank_name TEXT NOT NULL DEFAULT 'Cuve Principale',
  driver_name TEXT,
  truck_plate TEXT,
  receiver_name TEXT NOT NULL DEFAULT '',
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 9. Table Ajustements de Jauge
CREATE TABLE IF NOT EXISTS public.stock_adjustments (
  id TEXT PRIMARY KEY,
  date TEXT NOT NULL,
  previous_stock DOUBLE PRECISION NOT NULL,
  new_stock DOUBLE PRECISION NOT NULL,
  difference DOUBLE PRECISION NOT NULL,
  reason TEXT NOT NULL DEFAULT '',
  adjusted_by TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 10. Table Utilisateurs & Opérateurs (avec Licences & Sous-Admins)
CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uid TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'POMPISTE',
  department TEXT NOT NULL DEFAULT '',
  active BOOLEAN NOT NULL DEFAULT true,
  avatar TEXT,
  password TEXT,
  client_company_name TEXT,
  client_phone TEXT,
  license_type TEXT DEFAULT 'MENSUEL',
  license_price DOUBLE PRECISION DEFAULT 0,
  license_expires_at TEXT,
  subscription_status TEXT DEFAULT 'ACTIF',
  suspension_reason TEXT,
  max_vehicles_quota INTEGER DEFAULT 50,
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Migration automatique des colonnes si la table existe déjà
DO $$ 
BEGIN
  ALTER TABLE public.users ADD COLUMN IF NOT EXISTS client_company_name TEXT;
  ALTER TABLE public.users ADD COLUMN IF NOT EXISTS client_phone TEXT;
  ALTER TABLE public.users ADD COLUMN IF NOT EXISTS license_type TEXT DEFAULT 'MENSUEL';
  ALTER TABLE public.users ADD COLUMN IF NOT EXISTS license_price DOUBLE PRECISION DEFAULT 0;
  ALTER TABLE public.users ADD COLUMN IF NOT EXISTS license_expires_at TEXT;
  ALTER TABLE public.users ADD COLUMN IF NOT EXISTS subscription_status TEXT DEFAULT 'ACTIF';
  ALTER TABLE public.users ADD COLUMN IF NOT EXISTS suspension_reason TEXT;
  ALTER TABLE public.users ADD COLUMN IF NOT EXISTS max_vehicles_quota INTEGER DEFAULT 50;
  ALTER TABLE public.users ADD COLUMN IF NOT EXISTS notes TEXT;
END $$;

-- Activer Row Level Security (RLS) & Politiques d'accès public/authentifié
ALTER TABLE public.company_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stock_configs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vehicle_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.departments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vehicles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.suppliers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fuel_exits ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fuel_deliveries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stock_adjustments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

-- Politiques RLS permissives pour l'application Gascons
DO $$ 
BEGIN
  DROP POLICY IF EXISTS "Allow public read-write for company_profiles" ON public.company_profiles;
  DROP POLICY IF EXISTS "Allow public read-write for stock_configs" ON public.stock_configs;
  DROP POLICY IF EXISTS "Allow public read-write for vehicle_categories" ON public.vehicle_categories;
  DROP POLICY IF EXISTS "Allow public read-write for departments" ON public.departments;
  DROP POLICY IF EXISTS "Allow public read-write for vehicles" ON public.vehicles;
  DROP POLICY IF EXISTS "Allow public read-write for suppliers" ON public.suppliers;
  DROP POLICY IF EXISTS "Allow public read-write for fuel_exits" ON public.fuel_exits;
  DROP POLICY IF EXISTS "Allow public read-write for fuel_deliveries" ON public.fuel_deliveries;
  DROP POLICY IF EXISTS "Allow public read-write for stock_adjustments" ON public.stock_adjustments;
  DROP POLICY IF EXISTS "Allow public read-write for users" ON public.users;

  CREATE POLICY "Allow public read-write for company_profiles" ON public.company_profiles FOR ALL USING (true) WITH CHECK (true);
  CREATE POLICY "Allow public read-write for stock_configs" ON public.stock_configs FOR ALL USING (true) WITH CHECK (true);
  CREATE POLICY "Allow public read-write for vehicle_categories" ON public.vehicle_categories FOR ALL USING (true) WITH CHECK (true);
  CREATE POLICY "Allow public read-write for departments" ON public.departments FOR ALL USING (true) WITH CHECK (true);
  CREATE POLICY "Allow public read-write for vehicles" ON public.vehicles FOR ALL USING (true) WITH CHECK (true);
  CREATE POLICY "Allow public read-write for suppliers" ON public.suppliers FOR ALL USING (true) WITH CHECK (true);
  CREATE POLICY "Allow public read-write for fuel_exits" ON public.fuel_exits FOR ALL USING (true) WITH CHECK (true);
  CREATE POLICY "Allow public read-write for fuel_deliveries" ON public.fuel_deliveries FOR ALL USING (true) WITH CHECK (true);
  CREATE POLICY "Allow public read-write for stock_adjustments" ON public.stock_adjustments FOR ALL USING (true) WITH CHECK (true);
  CREATE POLICY "Allow public read-write for users" ON public.users FOR ALL USING (true) WITH CHECK (true);
END $$;
`;
